

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL DEFAULT '',
  `encrypted_password` varchar(255) DEFAULT '',
  `reset_password_token` varchar(255) DEFAULT NULL,
  `reset_password_sent_at` datetime DEFAULT NULL,
  `remember_created_at` datetime DEFAULT NULL,
  `sign_in_count` int(11) NOT NULL DEFAULT '0',
  `current_sign_in_at` datetime DEFAULT NULL,
  `last_sign_in_at` datetime DEFAULT NULL,
  `current_sign_in_ip` varchar(255) DEFAULT NULL,
  `last_sign_in_ip` varchar(255) DEFAULT NULL,

  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,

  `invitation_token` varchar(255) DEFAULT NULL,
  `invitation_created_at` datetime DEFAULT NULL,
  `invitation_sent_at` datetime DEFAULT NULL,
  `invitation_accepted_at` datetime DEFAULT NULL,
  `invitation_limit` int(11) DEFAULT NULL,
  `invited_by_id` int(11) DEFAULT NULL,
  `invited_by_type` varchar(255) DEFAULT NULL,
  `invitations_count` int(11) DEFAULT '0',

  `phone` varchar(255) DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `avatar_file_name` varchar(255) DEFAULT NULL,
  `avatar_content_type` varchar(255) DEFAULT NULL,
  `avatar_file_size` int(11) DEFAULT NULL,
  `avatar_updated_at` datetime DEFAULT NULL,
  `content_group_id` int(11) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `header_file_name` varchar(255) DEFAULT NULL,
  `header_content_type` varchar(255) DEFAULT NULL,
  `header_file_size` int(11) DEFAULT NULL,
  `header_updated_at` datetime DEFAULT NULL,

  `is_pharma` tinyint(1) DEFAULT '0',
  `sponsor_id` int(11) DEFAULT NULL,
  `country_iso_code` varchar(255) DEFAULT NULL,

  `profession_id` int(11) DEFAULT NULL,
  `specialty_id` int(11) DEFAULT NULL,
  `employer_name` varchar(255) DEFAULT NULL,
  `firstname` varchar(255) DEFAULT NULL,
  `lastname` varchar(255) DEFAULT NULL,
  `app_locale` varchar(255) DEFAULT NULL,
  `physician_number` varchar(255) DEFAULT NULL,
  `has_only_web_content` tinyint(1) DEFAULT NULL,
  `web_content_url` varchar(255) DEFAULT NULL,
  `is_fictive_email` tinyint(1) DEFAULT '0',
  `accept_newsletter_mediconnect` tinyint(1) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
