<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */

return array('all'=>array('classView'=>'SmartyView',
                           'widgets'=>array('messages'=>null, 'alerts'=>null),                             
                          ),
            
     /* ======================== HELP================================================= */
     'ajaxListHelp'=>array( 
                                    'helpers'=>array('date'=>null),
                          "security"=>array("php_functions"=>array(                                                                                          
                                            "format_date"=>null
                                                 ),
                                ),
                            ),
     
      'ajaxListPartialHelp'=>array(
                               
                            'helpers'=>array('date'=>null),
           "security"=>array("php_functions"=>array(                                                                                          
                                            "format_date"=>null
                                                 ),
                                ),
                            ),
     
      'ajaxSaveNewHelpI18n'=>array(
                                    'template'=>"site_help_ajaxNewHelpI18n.tpl",  
      ), 
     
      'ajaxSaveHelpI18n'=>array(
                                    'template'=>"site_help_ajaxViewHelpI18n.tpl",  
      ), 
     
     
); 
 
