<?php

/*
 * Generated by SuperAdmin Generator date : 23/03/13 22:05:23
 */

return array(
    "default"=>array(
               "enabled"=>true,
               "actionEnabled"=>true, 
               "mode"=>'mixed'  // mixed : smarty View/Cache  | file: fichier  | uri  | header : header : only
    ),
   
        
        
   
      
          
      

   
     
    
            
);