<?php

/*
 * Generated by SuperAdmin Generator date : 23/03/13 22:05:23
 */

return array('all'=>array('classView'=>'SmartyView',
                           'widgets'=>array('messages'=>null),                             
                          ),
            
          
            
                          
                                  
                                  
                 
                 
                 
                 
                   
                 
                 
                   
                   
); 
 
