<?php

/*
 * Generated by SuperAdmin Generator date : 25/03/13 16:38:07
 */
 
class ModuleManagerAdminFormFilter extends mfFormFilterBase {
 
    protected $site=null;
    
    function __construct($site=null)
    {
      parent::__construct();
      $this->site=$site;
    }
    
    protected function getSite()
    {
     return $this->site;
    }
    
    function configure()
    {
        $this->setDefaults(array(
                       'order'=>array("id"=>"asc"),
                      'nbitemsbypage'=>"10",
       ));
       // Base Query
       $this->setQuery("SELECT * FROM ".moduleManagerAdmin::getTable().";");
       // Validators 
       $this->setValidators(array(       
            'order' => new mfValidatorSchema(array(
                                                        "id"=>new mfValidatorChoice(array("choices"=>array("asc","desc"),"required"=>false)),
                                                        "name"=>new mfValidatorChoice(array("choices"=>array("asc","desc"),"required"=>false)),
                                                        "type"=>new mfValidatorChoice(array("choices"=>array("asc","desc"),"required"=>false)),
                                                       ),array("required"=>false)),
            'search' => new mfValidatorSchema(array(   
                            "id"=>new mfValidatorString(array("required"=>false)),                            
                            "name"=>new mfValidatorString(array("required"=>false)),                            
                            ),array("required"=>false)), 
                            
             'equal' => new mfValidatorSchema(array(   
                                                      
                            "type"=>new mfValidatorChoice(array("choices"=>array(""=>"")+moduleManagerAdminUtils::getFieldValues('type') ,"required"=>false)),                            
                            ),array("required"=>false)),   
           'nbitemsbypage'=>new mfValidatorChoice(array("choices"=>array("5"=>"5","10"=>"10","20"=>"20","50"=>"50","100"=>"100","*"=>"*",))),         
        ));
    }
}


