--
-- Structure de la table `t_modules_admin`  Generated by SuperAdmin Generator date : 25/03/13 16:38:07
--
CREATE TABLE IF NOT EXISTS `t_modules_admin` (
        `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
        `name` varchar(128)  NOT NULL,
        `title` varchar(128) COLLATE utf8_general_ci NOT NULL,  
        `description` text  NOT NULL,  
        `logo` varchar(255)  NOT NULL,
        `type` varchar(48)  NOT NULL,
        `version` varchar(10)  NOT NULL,
        `mode` varchar(4) NOT NULL DEFAULT '',
        `is_active` enum('YES','NO')  NOT NULL DEFAULT 'NO',
        `created_at` timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` timestamp  NOT NULL DEFAULT '0000-00-00 00:00:00',
      PRIMARY KEY (`id`),
      UNIQUE KEY `unique_name` (`name`)     
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;


