<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class site_gallery_ajaxDeleteGalleryAction extends mfAction {
    
   
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      {         
          $validator=new mfValidatorInteger();
          $id=$validator->isValid($request->getPostParameter('SiteGallery'));               
          $item= new SiteGallery($id);              
          $item->delete();                   
          $response = array("action"=>"DeleteGallery","id" =>$id,"info"=>__("Gallery has been deleted."));
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

