<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
require_once dirname(__FILE__)."/ajaxListPartialPictureAction.class.php";

class site_gallery_ajaxListPictureAction extends site_gallery_ajaxListPartialPictureAction {
    

}