<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 21:56:09
 */

 class SocialNetworkBaseForm extends mfForm {
 
   // All fields excepted foreign keys
   
    function configure()
    {
        $this->setValidators(array(
            "id"=>new mfValidatorInteger(),                      
            "name"=>new mfValidatorName(array("max_length"=>"64")),   
            "link"=>new mfValidatorString(array("max_length"=>"255")),    
            "awe"=>new mfValidatorString(array("max_length"=>"64","required"=>false)),    
            "is_active"=>new mfValidatorChoice(array("choices"=>array("YES","NO"),)),  
            "picture"=>new mfValidatorFile(array(
                                    'required'=>false,                                   
                                    'mime_types' => 'web_images',
                                    'max_size'=>200000,                                   
                                                 )
                                            )
            )                         
        );
    }
    
 
}


