<?php

/*
 * Generated by generator date : 23/03/13 21:59:25
 */
 
class modules_manager_ajaxRefreshModuleManagerAdminAction extends mfAction {
    
    
    
    function execute(mfWebRequest $request) { 
    
      $messages = mfMessages::getInstance();
      try 
      {
          moduleManagerAdminUtils::refreshModulesList();
         $messages->addInfo(__('modules structure has been refresh.'));
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      $this->forward('modules_manager','ajaxListPartialModuleManagerAdmin');
    }

}

