<?php
/*
 * Generated by SuperAdmin Generator date : 25/03/13 22:41:46
 */
 
class modules_manager_ajaxChangeIsActiveModuleManagerAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
     
    function execute(mfWebRequest $request) {   
      $messages = mfMessages::getInstance();   
      try 
      {         
          $form=new moduleManagerChangeForm();
          $form->bind($request->getPostParameter('moduleManager'));
          if ($form->isValid())
          {
             $item= new ModuleManager($form->getValue('id'));    
             if ($item->isLoaded())
             {  
                if ($item->IsActiveNotAuthorized())
                    throw new mfException(__("operation is not authaurized."));
                $value=((string)$form['value']=='YES')?"NO":"YES"; 
                $item->set('is_active',$value);
                $item->save();
                $item->getModule()->removeConfigCache();
                $this->getContext()->getEventManager()->notify(new mfEvent($item, 'module.manager.change'));   
                // $this->getEventDispather()->notify(new mfEvent($item, 'moduleManager.change','change')); 
                $response = array("action"=>"ChangeIsActiveModuleManager","id"=>$item->get('id'),"state" =>$value);
             }
          }    
          else
          {
              $messages->addErrors(array_merge($form->getErrorSchema()->getGlobalErrors(),$form->getErrorSchema()->getErrors()));
          }             
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

