<?php

/*
 * Generated by SuperAdmin Generator date : 25/03/13 16:38:07
 */
 
require_once __DIR__."/ajaxListPartialModuleManagerAction.class.php";

class modules_manager_ajaxListModuleManagerAction extends modules_manager_ajaxListPartialModuleManagerAction {
    

}
