<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */

return array(
    "default"=>array(
                   "enabled"=>true,
             //    "cacheEnabled"=>true,
                  "mode"=>"mixed"
    ),
    
        
    
      
);