<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */

return array('all'=>array('classView'=>'SmartyView',
                           'widgets'=>array('messages'=>null, 'alerts'=>null),                             
                          ),
            
     /* ======================== HELP================================================= */
     'ajaxListWarning'=>array( 
                                    'helpers'=>array('date'=>null),
                          "security"=>array("php_functions"=>array(                                                                                          
                                            "format_date"=>null
                                                 ),
                                ),
                            ),
     
      'ajaxListPartialWarning'=>array(
                               
                            'helpers'=>array('date'=>null),
           "security"=>array("php_functions"=>array(                                                                                          
                                            "format_date"=>null
                                                 ),
                                ),
                            ),
     
      'ajaxSaveNewWarningI18n'=>array(
                                    'template'=>"site_warning_ajaxNewWarningI18n.tpl",  
      ), 
     
      'ajaxSaveWarningI18n'=>array(
                                    'template'=>"site_warning_ajaxViewWarningI18n.tpl",  
      ), 
     
     
); 
 
