<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 15:19:56
 */
 
class social_networks_ajaxPositionsSocialAction extends mfAction {

     function execute(mfWebRequest $request) {
        $messages = mfMessages::getInstance();     
        $this->user=$this->getUser();       
        $this->item_i18n=new SocialNetwork($request->getPostParameter('SocialNetwork'));              
        $this->form=new SocialNetworkPositionsForm($request->getPostParameter('SocialNetwork'));
        if (!$request->isMethod('POST') || !$request->getPostParameter('SocialNetwork'))
            return ;       
        $this->form->bind($request->getPostParameter('SocialNetwork'));
        if ($this->form->isValid())
        {           
           // PartnerWorkFeature::updatePositions($this->form->getPositions());
            
            var_dump($this->form->getPositions());
            
            $messages->addInfo(__('SocialNetwork have been updated.'));                     
            $this->forward($this->getModuleName(),'ajaxListPartialSocial');
        }  
        else 
        {
            //  echo "<pre>"; var_dump($this->form->getErrorSchema()->getErrorsMessage()); echo "</pre>";
             $messages->addError(__('Form has some errors.'));      
        } 
    }
    
    
//    function execute(mfWebRequest $request) {   
//        $messages = mfMessages::getInstance();
//        try 
//        {                 
//            $this->collection = SocialNetworkUtils::getCollectionByPosition();              
//        } 
//        catch (mfException $e) {
//            $messages->addError($e);
//        }
//        
//    }

}

