<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class social_networks_ajaxDeletePictureSocialAction extends mfAction {
    
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();
      try 
      {        
         $item=new SocialNetwork($request->getPostParameter('socialnetwork'));
         if ($item->isLoaded())
         {    
            $item->deletePicture();           
            $response = array("action"=>"deletePictureSocial",
                              "id" =>$item->get('id')
                          );
         }    
      } 
      catch (mfException $e) {
           $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

