<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 21:56:09
 */
 
class social_networks_ajaxDeleteSocialAction extends mfAction {
    
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      {
          
          $validator=new mfValidatorInteger();
          $id=$validator->isValid($request->getPostParameter('SocialNetwork'));
          $item= new SocialNetwork($id);
          $item->delete();          
        //  $this->getEventDispather()->notify(new mfEvent($item, 'taxes.change','delete')); 
          $response = array("action"=>"DeleteSocial","id" =>$id);
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

