<?php


class mfCronConfigHandler extends mfFileLoaderConfigHandler {
    
    function execute($configFiles)
    {
         $data=array();         
         $configs=$this->parse($configFiles);         
         $data[]=sprintf('return unserialize(%s);', var_export(serialize($configs), true));
         $retval=sprintf("<?php\n".
                   "// auto-generated by mfCronConfigHandler\n".
                   "// date: %s\n%s\n", date('Y/m/d H:i:s'), implode("\n", $data)
         );
         return $retval;
    }

    
    function parse($configFiles)
    {
        $crons=array();
        foreach ($configFiles as $file)
              $crons=array_merge($crons,include $file);
        return $crons;
    }
    
}

