<?php

/*
 * Generated by SuperAdmin Generator date : 05/06/13 23:04:58
 */

 class SystemModelTextBaseForm extends mfForm {
 
   // All fields excepted foreign keys
   
    function configure()
    {
        $this->setValidators(array(
            "id"=>new mfValidatorInteger(),                                    
            "name"=>new mfValidatorName(array("required"=>false,"max_length"=>64)),  
            "type"=>new mfValidatorChoice(array("choices"=>array(""=>"","SYSTEM"=>"SYSTEM"),"key"=>true,"required"=>false)),
            "orientation"=>new mfValidatorChoice(array("choices"=>array("Landscape"=>__("Landscape"),"Portrait"=>__("Portrait")),"key"=>true,"required"=>false)),
            "size"=>new mfValidatorChoice(array("choices"=>array("A4"=>__("A4")),"key"=>true,"required"=>false)),
            ) 
        );
    }
    
 
}


