<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 17:43:38
 */
 
class social_networks_ajaxMoveSocialAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
 
    function execute(mfWebRequest $request) {   
        $messages = mfMessages::getInstance();            
        $response=array();
        try {
           $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);  
           if (!$site) 
              throw new mfException(__("thanks to select a site"));            
            $form=new movePositionForm();
            $form->bind($request->getPostParameter('socialnetwork'));
            if ($form->isValid())
            {
                $item=new SocialNetwork($form->getValue('id'),$site);
                $item->moveTo($form->getValue('node'));
                $item->save();             
                $response=array("action"=>"moveSocialNetwork","id"=>$item->get('id'),"info"=>__("social network has been moved."));
            }               
        } catch (mfException $e) {
            $messages->addError($e);
        }
        return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

