<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 15:19:56
 */
 
class social_networks_ajaxPositionsSocialAction extends mfAction {

    const SITE_NAMESPACE = 'system/site';
    
    function execute(mfWebRequest $request) {   
        $messages = mfMessages::getInstance();
        try 
        {
            $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);  
            $this->forwardIf(!$site,"sites","Admin");            
            $this->collection = SocialNetworkUtils::getCollectionByPosition($site);              
        } 
        catch (mfException $e) {
            $messages->addError($e);
        }
        
    }

}

