<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 21:56:09
 */
 
class social_networks_ajaxViewSocialAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
    
        
    function execute(mfWebRequest $request) {             
        $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);    
        $this->forwardIf(!$site,"sites","Admin");
        $messages = mfMessages::getInstance();
        $this->form = new SocialNetworkViewForm();
        $this->item=new SocialNetwork($request->getPostParameter('id'),$site);                             
   }

}

