<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class social_networks_ajaxDeletePictureSocialAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();
      try 
      {
         $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);
         if (!$site)
            return "";
         $item=new SocialNetwork($request->getPostParameter('socialnetwork'),$site);
         if ($item->isLoaded())
         {    
            $item->deletePicture();
            //$this->getEventDispather()->notify(new mfEvent($item, 'product.change','delete.picture')); 
            $response = array("action"=>"deletePictureSocial",
                              "id" =>$item->get('id')
                          );
         }    
      } 
      catch (mfException $e) {
           $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

