<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 21:56:09
 */
 
class social_networks_ajaxDeleteSocialAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
    
    function execute(mfWebRequest $request) {      
      $messages = mfMessages::getInstance();   
      try 
      {
          $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);
          if (!$site) 
              throw new mfException(__("thanks to select a site"));    
          $validator=new mfValidatorInteger();
          $id=$validator->isValid($request->getPostParameter('socialnetwork'));
          $item= new SocialNetwork($id,$site);
          $item->delete();          
        //  $this->getEventDispather()->notify(new mfEvent($item, 'taxes.change','delete')); 
          $response = array("action"=>"deleteSocial","id" =>$id);
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

