<?php
/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class social_networks_ajaxChangeIsActiveSocialAction extends mfAction {
    
    const SITE_NAMESPACE = 'system/site';
     
    function execute(mfWebRequest $request) {   
      $messages = mfMessages::getInstance();   
      try 
      {
          $site=$this->getUser()->getStorage()->read(self::SITE_NAMESPACE);     
          if (!$site)  
               throw new mfException(__("thanks to select a site"));  
          $form=new SocialNetworkChangeForm();
          $form->bind($request->getPostParameter('socialnetwork'));
          if ($form->isValid())
          {
             $item= new SocialNetwork($form->getValue('id'),$site);    
             if ($item->isLoaded())
             {  
                $value=((string)$form['value']=='YES')?"NO":"YES"; 
                $item->set('is_active',$value);
                $item->save();
                // $this->getEventDispather()->notify(new mfEvent($item, 'product.change','change')); 
                $response = array("action"=>"ChangeIsActiveSocial","id"=>$item->get('id'),"state" =>$value);
             }
          }    
          else
          {
              $messages->addErrors(array_merge($form->getErrorSchema()->getGlobalErrors(),$form->getErrorSchema()->getErrors()));
          }             
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasErrors()?array("error"=>$messages->getDecodedErrors()):$response;
    }

}

