<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 21:56:09
 */
 
require_once dirname(__FILE__)."/ajaxListPartialSocialAction.class.php";

class social_networks_ListSocialAction extends social_networks_ajaxListPartialSocialAction {
    

}

