<?php

/*
 * Generated by SuperAdmin Generator date : 25/03/13 16:38:07
 */

return array(
    "default"=>array(
                   "enabled"=>true,
             //    "cacheEnabled"=>true,
                  "mode"=>"mixed"
    ),
    
          
);