<?php

/*
 * Generated by generator date : 25/03/13 16:38:07
 */
 
class moduleManagerCollection extends mfObjectCollection2 {
    
    function __construct($data=null)
    {        
      parent::__construct($data,null,$site);
    }
    
    protected function executeSelectQuery($db)
    {
       $db->setQuery("SELECT * FROM ".$this->getTable()." WHERE ".$this->getWhereConditions().";")
            ->makeSqlQuery();       
    }
    
    protected function executeDeleteQuery($db)
    {
       $db->setQuery("DELETE FROM ".$this->getTable()." WHERE ".$this->getWhereConditions().";")
           ->makeSqlQuery();   
    }            
    
    protected function executeInsertQuery($db)
    {
       $db->makeSqlQuery();   
    }   
    
    protected function executeUpdateQuery($db)
    {                    
        $db->setQuery("UPDATE ".$this->getTable()." SET " . $this->getFieldsForUpdate() . " WHERE ".$this->getWhereConditions().";")
           ->makeSqlQuery();   
    }
    
    protected function  update()
    {
       // var_dump($this);
        parent::update();
    }
    
    
    public function removeConfigCache()
    {
         $files=array_merge(glob(mfConfig::get('mf_cache_dir').'/sites/'.$this->getSiteHost().'/frontend/*/config/module_*_config_module_*.php'),
                            glob(mfConfig::get('mf_cache_dir').'/sites/'.$this->getSiteHost().'/admin/*/config/module_*_config_module_*.php'),
                            glob(mfConfig::get('mf_cache_dir').'/sites/'.$this->getSiteHost()."/frontend/*/config/module_*_config_module.php"),
                            glob(mfConfig::get('mf_cache_dir').'/sites/'.$this->getSiteHost()."/admin/*/config/module_*_config_module.php")
                           );            
         foreach ($files as $file)
         {
            if (is_readable($file)) 
                unlink($file);
         }    
         
     }
}

