<?php

/*
 * Generated by SuperAdmin Generator date : 28/04/13 21:56:09
 */
 
class SocialNetworkUtilsBase {
    
  
    static function getFieldValuesForSelect($name,$site=null)
    {
        $values=array();
        $db=mfSiteDatabase::getInstance()
                ->setParameters(array("name"=>$name))
                ->setQuery("SELECT DISTINCT({name}),".  SocialNetwork::getKeyName()." FROM ".SocialNetwork::getTable()." ORDER BY {name} ASC;")               
                ->makeSiteSqlQuery($site); 
        if (!$db->getNumRows())
            return $values;
        while ($value=$db->fetchArray())
        { 
            $values[$value[SocialNetwork::getKeyName()]]=$value[$name];
        }      
        return $values;
    }     
    
     static function getMinimumDate($name,$site=null)
    {
        $db = mfSiteDatabase::getInstance()      
                ->setParameters(array('name'=>$name))
                ->setQuery("SELECT MIN(`{name}`) FROM ".  SocialNetwork::getTable().";")
                ->makeSiteSqlQuery($site);
        if ($db->getNumRows())
        {
          $row=$db->fetchRow();
          return $row[0];
        }
        else
        {
            return date("Y-m-d");
        }    
    }
    
    static function getCollectionByPosition($site=null)
    {
        $db=mfSiteDatabase::getInstance()
                ->setQuery("SELECT * FROM ".  SocialNetwork::getTable().                           
                           " ORDER BY position ASC;")               
                ->makeSiteSqlQuery($site); 
        if (!$db->getNumRows())
            return null;
        $items=array();
        while ($row=$db->fetchObject('SocialNetwork'))
            $items[]=$row;
        return $items;
    }
    
     static function initializeSite($site=null)
    {
        $db=mfSiteDatabase::getInstance()
                ->setQuery("DELETE FROM ".self::getTable().";")               
                ->makeSiteSqlQuery($site);    
       
    }  
    
     static function getActiveCollectionByPosition()
    {
        $items=new SocialNetworkCollection();
        $db=mfSiteDatabase::getInstance()
                ->setQuery("SELECT * FROM ".  SocialNetwork::getTable().    
                           " WHERE is_active='YES'".
                           " ORDER BY position ASC;")               
                ->makeSiteSqlQuery(); 
        if (!$db->getNumRows())
            return $items;     
        while ($item=$db->fetchObject('SocialNetwork'))
            $items[]=$item;
        return $items;
    }
}
