<?php

/*
 * Generated by SuperAdmin Generator date : 28/03/13 17:57:40
 */

return array(
    "default"=>array(
                   "enabled"=>true,
             //    "cacheEnabled"=>true,
                  "mode"=>"mixed"
    ),
    
        
    
      
);