<!DOCTYPE html >
<html xmlns="http://www.w3.org/1999/xhtml" lang="{$_request->getLanguage()}" xml:lang="{$_request->getLanguage()}">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="{url('/majestic/css/style.css','web','frontend')}">
	</head>
    <body>      
            {if $model_i18n && $model_i18n->isLoaded()}
               {eval $model_i18n->get('body')}
            {else}                   
        <div class="container email" style="font-size:16px;margin-left:100px;width: 30%;margin-top: 150px;">
          {$employee.courtesy} {$employee.gender.short} {$employee.firstname} {$employee.lastname}<br><br>
          Thank you so much for trying to post your offer. After carefully reviewing what outlined in your offer, we must regretfully decline it. The offer does not meet the requirements of our current rules, regulations, our community guidelines.<br>
              
            Please review our job posting policies, if you have any more questions contact our customer support by clicking in the link below.<br><br>
            Cordialement<br><br>{$company.commercial} Technology Team<br><br>
            ------
            <div class="LogoCompanyCongratEmail">
              <img title="Logo" class="logo" src="{$company.picture.url}" alt="Logo">              
            </div>
            {*<h3>{$company.web}</h3>*}
        </div>
            {/if}
    </body>
</html>

