<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */

return array('all'=>array('classView'=>'SmartyView',
                           'widgets'=>array('messages'=>null, 'alerts'=>null),                             
                          ),
            
    'ListPicture'=>array(
                   'layout'=>array(
                        "template"=>"layout_dashboard.xml",
                        ),
                 'stylesheets'=>array("main.css"=>null,
                                       "themes/base/jquery.ui.all.css"=>null,
                                     "ui.datepicker.css"=>null,                                                ),
                 'javascripts'=>array('jquery-1.7.min.js'=>null,
                                       'jquery.custom.js'=>null,
                                       'jquery.custom.messages.js'=>array("type"=>"url"),
                                       'ui/jquery-ui-1.8.20.custom.min.js'=>null,
                                      ), 
                  'title'=>"pictures", 
                  'blocks'=>array('JqueryScriptsReady'=>null),
                  'metas'=>array(
                                "description"=>"super web",
                                "keywords"=>"key1,key2...",
                              ),
                  'widgets'=>array("banner"=>null,

                       "stylesheets"=>null, 
                   ),     
                  'helpers'=>array(
                                "date"=>null, 

                                "number"=>null,                                                ),
                 'security'=>array(
                     "php_functions"=>array(
                                        "format_date"=>null,                                                         
                                        "format_pourcentage"=>null,                                                            
                                     ),
                      ), 
                  'functions'=>array(
                                   'html_options_format'=>null,                                                     
                                   ),
    ),
     
    'ajaxListPicture'=>array(
                   'functions'=>array(                                                       
                                       'html_options_format'=>null,                                                          
                                       ),
                   'blocks'=>array('JqueryScriptsReady'=>null),
                   "widgets"=>array("stylesheets"=>null),                                     
                   'stylesheets'=>array( 
                                          "ui.datepicker.css"=>null
                                      ),
                   'helpers'=>array(
                              "date"=>null,                                                 
                              "number"=>null),
                   'security'=>array(
                           "php_functions"=>array(
                              "format_date"=>null,                                                                                                                                                    
                              "format_pourcentage"=>null,                                                    
                           ),
                    ), 
   ),
                                  
    'ajaxListPartialPicture'=>array(
                    'functions'=>array(
                                        'html_options_format'=>null,                                                                                                                   
                                        ),
                    'blocks'=>array('JqueryScriptsReady'=>null),

                    'helpers'=>array(
                               "date"=>null,                                                 
                               "number"=>null),                                                
                    'security'=>array(
                            "php_functions"=>array(
                               "format_date"=>null,                                                                                                                                                            
                               "format_pourcentage"=>null,                                                                                                 
                             ),
                     ),                                                 
    ),
            
    "ajaxSaveNewPictureI18n"=>array(
                "template"=>"site_gallery_ajaxNewPictureI18n.tpl",
    ),      
    
     "ajaxViewPictureI18n"=>array(
                    'helpers'=>array(
                               "date"=>null,                                                 
                               "number"=>null),                                                
                    'security'=>array(
                            "php_functions"=>array(
                               "format_date"=>null,                                                                                                                                                            
                               "format_size"=>null,                                                                                                 
                             ),
                     ),  
    ),
    
     "ajaxSaveViewPictureI18n"=>array(
                "template"=>"site_gallery_ajaxViewPictureI18n.tpl",
                'helpers'=>array(
                               "date"=>null,                                                 
                               "number"=>null),                                                
                    'security'=>array(
                            "php_functions"=>array(
                               "format_date"=>null,                                                                                                                                                            
                               "format_size"=>null,                                                                                                 
                             ),
                     ),  
    ),   
    
    "ajaxDeletePictureI18n"=>array(
        
    ),
    
    /* =========================== G A L L E R Y ================================================= */
    
     'ListGallery'=>array(
                   'layout'=>array(
                        "template"=>"layout_dashboard.xml",
                        ),
                 'stylesheets'=>array("main.css"=>null,
                                       "themes/base/jquery.ui.all.css"=>null,
                                     "ui.datepicker.css"=>null,                                                ),
                 'javascripts'=>array('jquery-1.7.min.js'=>null,
                                       'jquery.custom.js'=>null,
                                       'jquery.custom.messages.js'=>array("type"=>"url"),
                                       'ui/jquery-ui-1.8.20.custom.min.js'=>null,
                                      ), 
                  'title'=>"galleries", 

                  'metas'=>array(
                                "description"=>"super web",
                                "keywords"=>"key1,key2...",
                              ),
                  'blocks'=>array('JqueryScriptsReady'=>null),
                  'widgets'=>array("banner"=>null,

                       "stylesheets"=>null, 
                   ),     
                  'helpers'=>array(
                                "date"=>null, 

                                "number"=>null,                                                ),
                 'security'=>array(
                     "php_functions"=>array(
                                        "format_date"=>null,                                                         
                                        "format_pourcentage"=>null,                                                            
                                     ),
                      ), 
                  'functions'=>array(
                                   'html_options_format'=>null,                                                     
                                   ),
    ),
     
    'ajaxListGallery'=>array(
                   'functions'=>array(                                                       
                                       'html_options_format'=>null,                                                          
                                       ),
                   'blocks'=>array('JqueryScriptsReady'=>null),
                   "widgets"=>array("stylesheets"=>null),                                     
                   'stylesheets'=>array( 
                                          "ui.datepicker.css"=>null
                                      ),
                   'helpers'=>array(
                              "date"=>null,                                                 
                              "number"=>null),
                   'security'=>array(
                           "php_functions"=>array(
                              "format_date"=>null,                                                                                                                                                    
                              "format_pourcentage"=>null,                                                    
                           ),
                    ), 
   ),
                                  
    'ajaxListPartialGallery'=>array(
                    'functions'=>array(
                                        'html_options_format'=>null,                                                                                                                   
                                        ),
                    'blocks'=>array('JqueryScriptsReady'=>null),

                    'helpers'=>array(
                               "date"=>null,                                                 
                               "number"=>null),                                                
                    'security'=>array(
                            "php_functions"=>array(
                               "format_date"=>null,                                                                                                                                                            
                               "format_pourcentage"=>null,                                                                                                 
                             ),
                     ),                                                 
    ),
    
    
    "ajaxSaveNewGalleryI18n"=>array(
                "template"=>"site_gallery_ajaxNewGalleryI18n.tpl",
                'helpers'=>array(                                                                                  
                                             "date"=>null,                                                
                                             ),                                     
                    'security'=>array(
                                    "php_functions"=>array(

                                                   "format_date"=>null, 
                                                            ),
                                     ), 
    ), 
    
    "ajaxNewGalleryI18n"=>array(
                    'helpers'=>array(                                                                                  
                                             "date"=>null,                                                
                                             ),                                     
                    'security'=>array(
                                    "php_functions"=>array(

                                                   "format_date"=>null, 
                                                            ),
                                     ), 
    ),
    
     "ajaxViewGalleryI18n"=>array(
                    'helpers'=>array(                                                                                  
                                             "date"=>null,                                                
                                             ),                                     
                    'security'=>array(
                                    "php_functions"=>array(

                                                   "format_date"=>null, 
                                                            ),
                                     ), 
    ),
    
    "ajaxSaveGalleryI18n"=>array(
                     'template'=>'site_gallery_ajaxViewGalleryI18n.tpl',
                     'helpers'=>array(                                                                                  
                                             "date"=>null,                                                
                                             ),                                     
                    'security'=>array(
                                    "php_functions"=>array(

                                                   "format_date"=>null, 
                                                            ),
                                     ), 
    ),
    
 /*    'ajaxSelectListFilterMultiplePicturesForGallery'=>array(
                   'functions'=>array(                                                       
                                       'html_options_format'=>null,                                                          
                                       ),
                   'blocks'=>array('JqueryScriptsReady'=>null),
                   "widgets"=>array("stylesheets"=>null),                                     
                   'stylesheets'=>array( 
                                          "ui.datepicker.css"=>null
                                      ),
                   'helpers'=>array(
                              "date"=>null,                                                 
                              "number"=>null),
                   'security'=>array(
                           "php_functions"=>array(
                              "format_date"=>null,                                                                                                                                                    
                              "format_pourcentage"=>null,                                                    
                           ),
                    ), 
   ),*/
    
      "ajaxListPartialPictureForGalleryI18n"=>array(              
                'helpers'=>array(
                               "date"=>null,                                                 
                               "number"=>null),                                                
                    'security'=>array(
                            "php_functions"=>array(
                               "format_date"=>null,                                                                                                                                                            
                               "format_size"=>null,                                                                                                 
                             ),
                     ),  
    ),  
    
    
 /*      "ajaxSavePictureI18nForGalleryI18n"=>array(   
                'template'=>'site_gallery_ajaxViewPictureI18nForGalleryI18n.tpl',
                'helpers'=>array(
                               "date"=>null,                                                 
                               "number"=>null),                                                
                    'security'=>array(
                            "php_functions"=>array(
                               "format_date"=>null,                                                                                                                                                            
                               "format_size"=>null,                                                                                                 
                             ),
                     ),  
    ),  */
); 
 
