<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */

 class CmsPageSettingsForm extends mfForm {
 
   
    function configure()
    {
        $this->setValidators(array(                        
            'site_map_changefreq'=>new mfValidatorChoice(array("key"=>true,"choices"=>array('always'=>'always','hourly'=>'hourly','daily'=>'daily','weekly'=>'weekly','monthly'=>'monthly','yearly'=>'yearly','never'=>'never'))),            
            "site_map_priority"=>new mfValidatorI18nNumber(array('min'=>0,'max'=>1))
            ) 
        );
    }
    
 
}


