<?php

/*
 * Generated by SuperAdmin Generator date : 24/04/13 15:45:29
 */
 
class users_guard_ajaxDeleteSessionAction extends mfAction {
    
   function execute(mfWebRequest $request) {     
      $messages = mfMessages::getInstance();   
      try 
      {         
          $validator=new mfValidatorInteger();
          $session= new EmployeeSession(array('id'=>$validator->isValid($request->getPostParameter('Session'))));
          if ($session->isLoaded())
          {    
            $session->set('status','DELETE');
            $session->delete();
            // $response = array("action"=>"deletePermissionGroupI18n","id" =>$id,"info"=>__("Permission group has been deleted."));
            $response = array("action"=>"DeleteSession","id" =>$session->get('id'));
          }
      } 
      catch (mfException $e) {
          $messages->addError($e);
      }
      return $messages->hasMessages('error')?array("error"=>$messages->getDecodedErrors()):$response;
    }
}

