<?php

class mfMenuConfigHandler extends mfMenuConfigHandlerCore {

    protected function addChilds($childs,&$menu) 
    {       
        ksort($childs);                
        parent::addChilds($childs, $menu);
    }  
    
    function execute($configFiles) {        
        
        $site=$this->getParameters()->get('site');        
        MenuTranslator::removeCache($site);// Remove i18n cache
        $selectorName=$this->getParameters()->get('parameters');
        $classModuleManager=$this->getParameters()->get('class');        
        if ($classModuleManager && class_exists($classModuleManager))
        {
            $configFiles=$classModuleManager::getInstance()->getConfigFiles($configFiles,$site);
        }              
        $data=$this->buildMenu($configFiles,$selectorName,$selectorName."_menu");            
        $retval=sprintf("<?php\n".
                   "// auto-generated by ".get_class($this)."\n".
                   "// date: %s\n%s\n", date('Y/m/d H:i:s'), implode("\n", $data)
        );
        return $retval;
    }
    
}

