<?php

/*
 * Generated by SuperAdmin Generator date : 25/03/13 16:38:07
 */

class modules_managerUninstall extends mfModuleInstall {
    
    function execute()
    {
       
       $importDB=importDatabase::getInstance();
       $site=$this->getSite();
       $files=array(
                 $this->getModelsPath()."/drop.sql",                
                   );
        
       if (mfConfig::getSuperAdmin('site')==$site->getSiteName())
          $files[]= $this->getModelsPath()."/drop_superadmin.sql";
             
       foreach ($files as $file)
       {             
         if (is_readable($file))
            $importDB->import($file,$site);
       }   

       return true;
    }
    
}


