<?php

/*
 * Generated by SuperAdmin Generator date : 25/03/13 16:38:07
 */

return array('all'=>array('classView'=>'SmartyView',
                           'widgets'=>array('messages'=>null),                             
                          ),
            
                          'listModuleManager'=>array(
                                   'layout'=>array(
                                        "template"=>"layout_site.xml",
                                        ),
                                 'stylesheets'=>array("main.css"=>null,
                                                       "themes/base/jquery.ui.all.css"=>null,
                                                                                                     ),
                                 'javascripts'=>array('jquery-1.7.min.js'=>null,
                                                       'jquery.custom.js'=>null,
                                                       'jquery.custom.messages.js'=>array("type"=>"url"),
                                                       'ui/jquery-ui-1.8.20.custom.min.js'=>null,
                                                      ), 
                                  'title'=>"modules | manager | admin", 
                           
                                  'metas'=>array(
                                                "description"=>"super web",
                                                "keywords"=>"key1,key2...",
                                              ),
                                  'widgets'=>array("banner"=>null,
                                      
                                        
                                   ),     
                                  'helpers'=>array(
                                                 
                                                
                                                                                                ),
                                 'security'=>array(
                                     "php_functions"=>array(
                                                         
                                                        
                                                         
                                                     ),
                                      ), 
                                  'functions'=>array(
                                                      
                                                   
                                                   'html_options_format'=>null
                                                   ),
                                  'blocks'=>array('JqueryScriptsReady'=>null)
                                  ),
     
                 'ajaxListModuleManager'=>array(
                                     'functions'=>array(
                                                         'html_options_format'=>null,
                                                          
                                                         
                                                         ),
                                     
                                      'blocks'=>array('JqueryScriptsReady'=>null),
                                                                          'stylesheets'=>array( 
                                                                          ),
                                     'helpers'=>array(
                                                 
                                                
                                                                                                ),
                                     'security'=>array(
                                             "php_functions"=>array(
                                                 
                                                
                                                 
                                                                  ),
                                      ), 
                                  ),
                                  
                 'ajaxListPartialModuleManager'=>array(
                                     'functions'=>array(
                                                         'html_options_format'=>null,
                                                          
                                                         
                                                         ),
                                    
                                     'helpers'=>array(
                                                 
                                                
                                                                                                ),
                                                
                                     'security'=>array(
                                             "php_functions"=>array(
                                                 
                                                
                                                 
                                                
                                                             ),
                                      ),                                                 
                                   ),
            
            
                          
                                  
                                  
                 
                 
                 
                 
                   
                 
                 
                   
           
                          'listModuleManagerAdmin'=>array(
                                   'layout'=>array(
                                        "template"=>"layout_dashboard.xml",
                                        ),
                                 'stylesheets'=>array("main.css"=>null,
                                                       "themes/base/jquery.ui.all.css"=>null,
                                                                                                     ),
                                 'javascripts'=>array('jquery-1.7.min.js'=>null,
                                                       'jquery.custom.js'=>null,
                                                       'jquery.custom.messages.js'=>array("type"=>"url"),
                                                       'ui/jquery-ui-1.8.20.custom.min.js'=>null,
                                                      ), 
                                  'title'=>"modules | manager | admin", 
                           
                                  'metas'=>array(
                                                "description"=>"super web",
                                                "keywords"=>"key1,key2...",
                                              ),
                                  'widgets'=>array("banner"=>null,
                                      
                                        
                                   ),     
                                  'helpers'=>array(
                                                 
                                                
                                                                                                ),
                                 'security'=>array(
                                     "php_functions"=>array(
                                                         
                                                        
                                                         
                                                     ),
                                      ), 
                                  'functions'=>array(
                                                   'html_options_format'=>null,   
                                                   
                                                 //  'html_options_i18n'=>null
                                                   ),
                                  'blocks'=>array('JqueryScriptsReady'=>null)
                                  ),
     
                 'ajaxListModuleManagerAdmin'=>array(
                                     'functions'=>array(
                                                       //  'html_options_i18n'=>null,
                                                           'html_options_format'=>null,   
                                                         
                                                         ),
                                     'blocks'=>array('JqueryScriptsReady'=>null),
                                     
                                                                          'stylesheets'=>array( 
                                                                          ),
                                     'helpers'=>array(
                                                 
                                                
                                                                                                ),
                                     'security'=>array(
                                             "php_functions"=>array(
                                                 
                                                
                                                 
                                                                  ),
                                      ), 
                                  ),
                                  
                 'ajaxListPartialModuleManagerAdmin'=>array(
                                     'functions'=>array(
                                                     //    'html_options_i18n'=>null,
                                                         'html_options_format'=>null,     
                                                         
                                                         ),
                                     'blocks'=>array('JqueryScriptsReady'=>null),
                                     
                                     'helpers'=>array(
                                                 
                                                
                                                                                                ),
                                                
                                     'security'=>array(
                                             "php_functions"=>array(
                                                 
                                                
                                                 
                                                
                                                             ),
                                      ),                                                 
                                   ),
            
            
                          
                                  
                                  
                 
         "ajaxSaveLoadModuleManagerAdmin"=>array(
                "template"=>"modules_manager_ajaxLoadModuleManagerAdmin.tpl"
         ), 
                 
                 
                   
                 
                 
                   
                   
); 
 
