<?php

/*
 * Generated by SuperAdmin Generator date : 24/03/13 15:58:17
 */
 
class moduleManagerAdminLogoForm extends mfForm {

    function configure() { 
        $this->setValidators(array(
            'id'=>new mfValidatorInteger(), 
            'logo'=>new mfValidatorFile(array(
                                    'required'=>false,
                                    'mime_types' => 'web_images',
                                    'max_size'=>200000,
                                    'filename'=>"logo",
                                                 )
                                            ))
                );
    }
}