<?php
/*
 * Generated by SuperAdmin Generator date : 25/03/13 16:38:07
 */

class moduleManagerChangeForm extends mfForm {
    
    function configure()
    {
        $this->setValidators(array(
                 "id"=>new mfValidatorInteger(),
                 "value"=> new mfValidatorChoice(array("choices"=>array("NO","YES")))
                ));
    }
}
