<?php

/*
 * Generated by SuperAdmin Generator date : 25/03/13 16:38:07
 */

 class moduleManagerBaseForm extends mfForm {
 
   // All fields excepted foreign keys
   
    function configure()
    {
        $this->setValidators(array(
            "id"=>new mfValidatorInteger(),            
            "name"=>new mfValidatorString(array("max_length"=>"128","required"=>false,)),                                    
            "type"=>new mfValidatorString(array("max_length"=>"10","required"=>false,)),            
            "status"=>new mfValidatorString(array("choices"=>array("loaded","installed","uninstalled"),"required"=>false,)),            
            "is_active"=>new mfValidatorChoice(array("choices"=>array("YES","NO"),)),            
            "is_available"=>new mfValidatorChoice(array("choices"=>array("YES","NO"),)),                                                            
            ) 
        );
    }
    
 
}


