<?php

/*
 * Generated by SuperAdmin Generator date : 07/04/13 22:05:06
 */

return array(
    "default"=>array(
                   "enabled"=>true,
             //    "cacheEnabled"=>true,
                  "mode"=>"mixed"
    ),
    
        
    
        
    
      
);