<?php

/*
 * Generated by SuperAdmin Generator date : 07/04/13 22:05:06
 */
 
return array(
  "items"=>array(   
                   "site_payments"=>array("childs"=>array("site.payments.admin"=>'',)                
                 ),                   
 // CHILDS     
   "site.payments.admin"=>array(
                    "title"=>"payments",
                   // "url"=>"/paiment/check/admin",
                    "urlAjax"=>"/module/payments/admin/Listpayments",                    
                    "picture"=>"/module/payments/pictures/payment.png",
                    "help"=>"module administration manager",
                    "credentials"=>array(),
                    "enabled"=>true,
                    "module"=>"",
                ),
                
                                
                   
                  
                                         
                   
                  


    ),
);