<?php

/*
 * Generated by SuperAdmin Generator date : 07/04/13 22:05:06
 */

return array(
    "default"=>array(
               "enabled"=>true,
               "actionEnabled"=>true, 
               "mode"=>'mixed'  // mixed : smarty View/Cache  | file: fichier  | uri  | header : header : only
    ),   
    
  "ajaxChangeIsActivepayment"=>array("mode"=>"json"),        
  
  "ajaxMovepayment"=>array("mode"=>"json"),  
    
  "ajaxSaveCountry"=>array("mode"=>"json"),  
  
  "ajaxSaveCurrencies"=>array("mode"=>"json"),  
  
  "ajaxSaveCurrency"=>array("mode"=>"json"),
    
);