<?php

/*
 * Generated by SuperAdmin Generator date : 07/04/13 22:05:06
 */

return array('all'=>array('classView'=>'SmartyView',
                           'widgets'=>array('messages'=>null),                             
                          ),
            
                        
                 
     'ajaxSettingspayments'=>array(                                    
                                     'blocks'=>array('JqueryScriptsReady'=>null),   
                                    
     ),  
    
     'ajaxSettingsDefaultspayments'=>array(                                    
                                     'blocks'=>array('JqueryScriptsReady'=>null),         
                                    
     ),  
                 
                 
     "_listTextI18n"=>array(
                        "plugins"=>array(
                            'functions'=>array(
                                          'html_options_format'=>null, 
                                              ),
                        )
     ),             
                 
     "ajaxListTextI18n"=>array(      
                            'template'=>"./blocks/payments_listTextI18n.tpl",
                            'functions'=>array(
                                          'html_options_format'=>null, 
                                              ),                    
     ),              
                   
           
     'ajaxViewTextI18n'=>array(
                               'blocks'=>array('JqueryScriptsReady'=>null),   
                               "javascripts"=>array(
                                                           "tiny_mce/3.4.6/jquery.tinymce.js"=>array("async"=>false),  
                                                   ),
                                
     ),      
    
    
     'ajaxSaveTextI18n'=>array(
                               'blocks'=>array('JqueryScriptsReady'=>null),   
                               'template'=>"payments_ajaxViewTextI18n.tpl",                               
     ),      
            
                          
     'ajaxNewTextI18n'=>array(
                               'blocks'=>array('JqueryScriptsReady'=>null),   
                               "javascripts"=>array(
                                                     "tiny_mce/3.4.6/jquery.tinymce.js"=>array("async"=>false),  
                                                   ),                                
     ),                                 
                                  
                 
     'ajaxListpayments'=>array('blocks'=>array('JqueryScriptsReady'=>null),
     ),
                                  
     'ajaxListPartialpayments'=>array('blocks'=>array('JqueryScriptsReady'=>null),
     ),           
                 
                
     "_listCountry"=>array(
                           'security'=>array(
                                                     "php_functions"=>array(                                                                    
                                                                     "format_zone"=>""
                                                                             ),
                                                      ),  
     ),              
); 
 
