<?php

/*
 * Generated by SuperAdmin Generator date : 05/06/13 23:04:58
 */

 class PermissionsGroupBaseForm extends mfForm {
 
   // All fields excepted foreign keys
   
    function configure()
    {
        $this->setValidators(array(
            "id"=>new mfValidatorInteger(),                                    
            "name"=>new mfValidatorString(array("required"=>false,"max_length"=>64)),               
            ) 
        );
    }
    
 
}


